# Generated by Django 4.2.4 on 2023-08-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_rename_date_joined_user_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='event_type',
            new_name='voucher_type',
        ),
    ]
