# Generated by Django 4.2.4 on 2023-08-18 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_event_type_voucher_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvoucher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
